services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - FIGMA_API_KEY=${FIGMA_API_KEY}
    restart: unless-stopped