services:
  figma-developer-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: figma-developer-mcp
    restart: unless-stopped
    ports:
      - "${PORT}:${EXPOSE_PORT}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - FIGMA_API_KEY=${FIGMA_API_KEY}
      # We don't include FIGMA_API_KEY here for security reasons, it should be provided when starting the container
    # Alternative commands for different execution modes
    # command: ["pnpm", "start:cli"]  # For CLI mode
    # command: ["pnpm", "start:http"] # For HTTP mode (default)